#████████╗██╗███╗░░░███╗░█████╗░██████╗░░█████╗░███╗░░██╗░█████╗░████████╗███████╗░█████╗░██╗░░░░░███████╗██████╗░████████╗
#╚══██╔══╝██║████╗░████║██╔══██╗██╔══██╗██╔══██╗████╗░██║██╔══██╗╚══██╔══╝██╔════╝██╔══██╗██║░░░░░██╔════╝██╔══██╗╚══██╔══╝
#░░░██║░░░██║██╔████╔██║███████║██║░░██║██║░░██║██╔██╗██║███████║░░░██║░░░█████╗░░███████║██║░░░░░█████╗░░██████╔╝░░░██║░░░
#░░░██║░░░██║██║╚██╔╝██║██╔══██║██║░░██║██║░░██║██║╚████║██╔══██║░░░██║░░░██╔══╝░░██╔══██║██║░░░░░██╔══╝░░██╔══██╗░░░██║░░░
#░░░██║░░░██║██║░╚═╝░██║██║░░██║██████╔╝╚█████╔╝██║░╚███║██║░░██║░░░██║░░░███████╗██║░░██║███████╗███████╗██║░░██║░░░██║░░░
#░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝╚═╝░░╚═╝╚═════╝░░╚════╝░╚═╝░░╚══╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚══════╝╚══════╝╚═╝░░╚═╝░░░╚═╝░░░
#
#plugin by Timur Rootkovskiy (Adminov)
#vk - @timurroot
#
text:
  0:
    - '&e╔'
    - '&e║ &rИгрок &b%nick% &rкупил &a%donate%'
    - '&e║ &rНа нашем сайте: &dwww.samplesite.ru'
    - '&e║ &rИгрок знает, что делает, укрепляя свою позицию в табе!'
    - '&e╚'
  1:
    - '&e╔'
    - '&e║ &rИгрок &b%nick% &rкупил &a%donate%'
    - '&e║ &rНа нашем сайте: &dwww.samplesite.ru'
    - '&e║ &rЧудо-печки, топовые стрелы и многое другое ждёт его!'
    - '&e╚'
  2:
    - '&e╔'
    - '&e║ &rИгрок &b%nick% &rкупил &a%donate%'
    - '&e║ &rНа нашем сайте: &dwww.samplesite.ru'
    - '&e║ &rОчень скоро возвысится новый донатер, трепещите!'
    - '&e╚'
  3:
    - '&e╔'
    - '&e║ &rИгрок &b%nick% &rкупил &a%donate%'
    - '&e║ &rНа нашем сайте: &dwww.samplesite.ru'
    - '&e║ &rC его нынешними возможностями - он богоподобен!'
    - '&e╚'
  4:
    - '&e╔'
    - '&e║ &rИгрок &b%nick% &rкупил &a%donate%'
    - '&e║ &rНа нашем сайте: &dwww.samplesite.ru'
    - '&e║ &rПопрошайки, налетайте, кому-то сегодня повезёт!'
    - '&e╚'
#
messages:
  noperm: "&c&lУ вас недостаточно прав!"
  complete: "&a&lСообщение успешно отправлено!"
  consolecomplete: "Kto-to kupil donat"
  usage: "/timadonatealert <Ник> <Донат> - Выслать сообщение в чат о покупке доната"
#
#thanks for use my plugin <3